services:
  mariadb:
    # image: mariadb #this will download offical mriadb for docker hub
    build: ./requirements/mariadb # means Go into requirements/mariadb/ and build the image using the Dockerfile found there.
    # restart: always #this form  https://hub.docker.com/_/mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD : ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE : ${MARIADB_DATABASE}
      MARIADB_USER : ${MARIADB_USER}
      MARIADB_PASSWORD : ${MARIADB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    ports:
      # - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/wwww/html
    networks:
      - inception
  
  # wordpress:
  #   build: ./requirements/wordpress
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception


volumes:
  mariadb_data:
networks:
  inception:
    driver: bridge

  